steps:
# Build
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/project-a6517156-5d0f-4642-954/gcp-cicd-app/app:latest'
  - '.'

# Push
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/project-a6517156-5d0f-4642-954/gcp-cicd-app/app:latest'

# Deploy to VM
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - compute
  - ssh
  - my-vm
  - --zone=us-central1-a
  - --command
  - |
      docker pull us-central1-docker.pkg.dev/project-a6517156-5d0f-4642-954/gcp-cicd-app/app:latest &&
      docker stop $(docker ps -q) || true &&
      docker rm $(docker ps -aq) || true &&
      docker run -d -p 80:80 us-central1-docker.pkg.dev/project-a6517156-5d0f-4642-954/gcp-cicd-app/app:latest

images:
- 'us-central1-docker.pkg.dev/project-a6517156-5d0f-4642-954/gcp-cicd-app/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY